package com.tekion.dynamodblocaldemo.service.beans;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.tekion.dynamodblocaldemo.service.requestDTOs.AuthorRequest;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@Accessors(chain = true)
@DynamoDBTable(tableName = "author")
public class Author {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    public static Author fromRequest(AuthorRequest authorRequest){
        return new Author()
                .setFirstName(authorRequest.getFirstName())
                .setLastName(authorRequest.getLastName());
    }
}
